# 指定环境
language: node_js

node_js:
- '5.6.0' #指定使用 node.js 最新的稳定版0.12

# 指定分支
branches:
  only:
  - master #这个分支应当使用自己的 Dev repo

# 配置 Hexo
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save

# 执行 Hexo 的编译操作
script:
- hexo clean
- hexo g
- hexo d
