language: node_js
node_js:
- 5.6.0
branches:
  only:
  - master
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo generate
- hexo deploy
before_install:
- openssl aes-256-cbc -K $encrypted_685efb6bfe78_key -iv $encrypted_685efb6bfe78_iv
  -in ci_rsa.enc -out ~/.ssh/ci_rsa -d
- chmod 600 ~/.ssh/ci_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/ci_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "muuyao"
- git config --global user.email wanngxiao@gmail.com
